import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialCreate1774450929744 implements MigrationInterface {
    name = 'InitialCreate1774450929744'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "OrderItems" ("item_id" SERIAL NOT NULL, "order id" integer NOT NULL, "product id" integer NOT NULL, "quantity" integer NOT NULL, "price at purchase" numeric(10,2) NOT NULL, CONSTRAINT "PK_7f27669d980d88ab29d25b37945" PRIMARY KEY ("item_id"))`);
        await queryRunner.query(`CREATE INDEX "IX_OrderItems_Product_Id" ON "OrderItems" ("product id") `);
        await queryRunner.query(`CREATE INDEX "IX_OrderItems_Order_Id" ON "OrderItems" ("order id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "OrderItems_pkey" ON "OrderItems" ("item_id") `);
        await queryRunner.query(`CREATE TABLE "DeliverySlots" ("slot_id" SERIAL NOT NULL, "start time" TIMESTAMP NOT NULL, "end time" TIMESTAMP NOT NULL, "is available" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_a91c28f404589a212c52c2e56c0" PRIMARY KEY ("slot_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "DeliverySlots_pkey" ON "DeliverySlots" ("slot_id") `);
        await queryRunner.query(`CREATE TABLE "Stores" ("store_id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "city" character varying(100) NOT NULL, "street" character varying(255) NOT NULL, "house number" character varying(20) NOT NULL, "working hours" character varying(100) NOT NULL, CONSTRAINT "PK_94b2ba83ad8d84b4efd3bd4fb3d" PRIMARY KEY ("store_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Stores_pkey" ON "Stores" ("store_id") `);
        await queryRunner.query(`CREATE TABLE "Orders" ("order_id" SERIAL NOT NULL, "user id" integer NOT NULL, "delivery address id" integer, "store id" integer, "delivery slot id" integer NOT NULL, "order date" TIMESTAMP NOT NULL DEFAULT now(), "status" character varying(50) NOT NULL, "total amount" numeric(10,2) NOT NULL, "payment method" character varying(50) NOT NULL, CONSTRAINT "PK_6e8c9a313479da38ab0430e3d7f" PRIMARY KEY ("order_id"))`);
        await queryRunner.query(`CREATE INDEX "IX_Orders_User_Id" ON "Orders" ("user id") `);
        await queryRunner.query(`CREATE INDEX "IX_Orders_Store_Id" ON "Orders" ("store id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "Orders_pkey" ON "Orders" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "IX_Orders_Slot_Id" ON "Orders" ("delivery slot id") `);
        await queryRunner.query(`CREATE INDEX "IX_Orders_Address_Id" ON "Orders" ("delivery address id") `);
        await queryRunner.query(`CREATE TABLE "LoyaltyTransactions" ("transaction_id" SERIAL NOT NULL, "user id" integer NOT NULL, "order id" integer, "transaction date" TIMESTAMP NOT NULL DEFAULT now(), "amount" integer NOT NULL, "reason" character varying(255) NOT NULL, CONSTRAINT "PK_c4ddb169b3aa9c51a9ea3a1df7f" PRIMARY KEY ("transaction_id"))`);
        await queryRunner.query(`CREATE INDEX "IX_Loyalty_User_Id" ON "LoyaltyTransactions" ("user id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "LoyaltyTransactions_pkey" ON "LoyaltyTransactions" ("transaction_id") `);
        await queryRunner.query(`CREATE INDEX "IX_Loyalty_Order_Id" ON "LoyaltyTransactions" ("order id") `);
        await queryRunner.query(`CREATE TABLE "addresses" ("address_id" SERIAL NOT NULL, "user_id" integer NOT NULL, "street" character varying(255) NOT NULL, "building" character varying(20) NOT NULL, "apartment" character varying(20), "city" character varying(100) NOT NULL, "postal_code" character varying(10) NOT NULL, CONSTRAINT "PK_7075006c2d82acfeb0ea8c5dce7" PRIMARY KEY ("address_id"))`);
        await queryRunner.query(`CREATE INDEX "ix_addresses_user_id" ON "addresses" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "addresses_pkey" ON "addresses" ("address_id") `);
        await queryRunner.query(`CREATE TABLE "users" ("user_id" SERIAL NOT NULL, "phone_number" character varying(20) NOT NULL, "email" character varying(255) NOT NULL, "name" character varying(100) NOT NULL, "password_hash" character varying(255) NOT NULL, CONSTRAINT "PK_96aac72f1574b88752e9fb00089" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "users_pkey" ON "users" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "unique_phone" ON "users" ("phone_number") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "users_phone_number_key" ON "users" ("phone_number") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "users_email_key" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "unique_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "Cart" ("cart_id" SERIAL NOT NULL, "user id" integer, "guest_session_id" character varying(255), CONSTRAINT "UQ_28beb32f4358ca4f58b7b70cf58" UNIQUE ("guest_session_id"), CONSTRAINT "PK_9c15d504288b8bf9bd23197c6ba" PRIMARY KEY ("cart_id"))`);
        await queryRunner.query(`CREATE INDEX "IX_Cart_User_Id" ON "Cart" ("user id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "Cart_guest_session_id_key" ON "Cart" ("guest_session_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "Cart_pkey" ON "Cart" ("cart_id") `);
        await queryRunner.query(`CREATE TABLE "CartItems" ("item_id" SERIAL NOT NULL, "cart id" integer NOT NULL, "product id" integer NOT NULL, "quantity" integer NOT NULL DEFAULT 1, CONSTRAINT "PK_b0981105e728d2b1b5504dd6416" PRIMARY KEY ("item_id"))`);
        await queryRunner.query(`CREATE INDEX "IX_CartItems_Product_Id" ON "CartItems" ("product id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "CartItems_pkey" ON "CartItems" ("item_id") `);
        await queryRunner.query(`CREATE INDEX "IX_CartItems_Cart_Id" ON "CartItems" ("cart id") `);
        await queryRunner.query(`CREATE TABLE "products" ("product_id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "description" text, "price" numeric(10,2) NOT NULL, "qty_in_stock" integer NOT NULL DEFAULT 0, "img_url" character varying(500), CONSTRAINT "PK_a8940a4bf3b90bd7ac15c8f4dd9" PRIMARY KEY ("product_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "products_pkey" ON "products" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "ix_products_name" ON "products" ("name") `);
        await queryRunner.query(`CREATE TABLE "categories" ("category_id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "parent_category_id" integer, "img_url" character varying(500), "accent_color" character varying(7), CONSTRAINT "UQ_8b0be371d28245da6e4f4b61878" UNIQUE ("name"), CONSTRAINT "PK_51615bef2cea22812d0dcab6e18" PRIMARY KEY ("category_id"))`);
        await queryRunner.query(`CREATE INDEX "ix_categories_parent_id" ON "categories" ("parent_category_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "categories_name_key" ON "categories" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "categories_pkey" ON "categories" ("category_id") `);
        await queryRunner.query(`CREATE TABLE "productcategories" ("category_id" integer NOT NULL, "product_id" integer NOT NULL, CONSTRAINT "PK_09a6f5e8b8af9a53af4fef3689f" PRIMARY KEY ("category_id", "product_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_08f97e9a05e74adaef6128b725" ON "productcategories" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7242d523537887eedc8cce31e1" ON "productcategories" ("product_id") `);
        await queryRunner.query(`ALTER TABLE "OrderItems" ADD CONSTRAINT "FK_794bd0cca8310553df4714f699b" FOREIGN KEY ("order id") REFERENCES "Orders"("order_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "OrderItems" ADD CONSTRAINT "FK_5bdb51d8c4daf5a5dfd4b4e0b73" FOREIGN KEY ("product id") REFERENCES "products"("product_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Orders" ADD CONSTRAINT "FK_3966000a0b5d5bae146ff496c7b" FOREIGN KEY ("delivery slot id") REFERENCES "DeliverySlots"("slot_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Orders" ADD CONSTRAINT "FK_61ed9f90daf27cb8aa7d72fe4d1" FOREIGN KEY ("store id") REFERENCES "Stores"("store_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Orders" ADD CONSTRAINT "FK_229fceba3c9564ad81d8e7aeb78" FOREIGN KEY ("user id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "LoyaltyTransactions" ADD CONSTRAINT "FK_74c6d21c228fa315e0a1cb8ba52" FOREIGN KEY ("order id") REFERENCES "Orders"("order_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "LoyaltyTransactions" ADD CONSTRAINT "FK_5e91c1253e8e230324528d5c652" FOREIGN KEY ("user id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "FK_16aac8a9f6f9c1dd6bcb75ec023" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Cart" ADD CONSTRAINT "FK_127459be714cf668235bb37094d" FOREIGN KEY ("user id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CartItems" ADD CONSTRAINT "FK_3825b9a8f4b5d604d0a68db42b0" FOREIGN KEY ("cart id") REFERENCES "Cart"("cart_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CartItems" ADD CONSTRAINT "FK_9c61cd0de1d64d225792732b149" FOREIGN KEY ("product id") REFERENCES "products"("product_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_de08738901be6b34d2824a1e243" FOREIGN KEY ("parent_category_id") REFERENCES "categories"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "productcategories" ADD CONSTRAINT "FK_08f97e9a05e74adaef6128b7257" FOREIGN KEY ("category_id") REFERENCES "categories"("category_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "productcategories" ADD CONSTRAINT "FK_7242d523537887eedc8cce31e10" FOREIGN KEY ("product_id") REFERENCES "products"("product_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "productcategories" DROP CONSTRAINT "FK_7242d523537887eedc8cce31e10"`);
        await queryRunner.query(`ALTER TABLE "productcategories" DROP CONSTRAINT "FK_08f97e9a05e74adaef6128b7257"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_de08738901be6b34d2824a1e243"`);
        await queryRunner.query(`ALTER TABLE "CartItems" DROP CONSTRAINT "FK_9c61cd0de1d64d225792732b149"`);
        await queryRunner.query(`ALTER TABLE "CartItems" DROP CONSTRAINT "FK_3825b9a8f4b5d604d0a68db42b0"`);
        await queryRunner.query(`ALTER TABLE "Cart" DROP CONSTRAINT "FK_127459be714cf668235bb37094d"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "FK_16aac8a9f6f9c1dd6bcb75ec023"`);
        await queryRunner.query(`ALTER TABLE "LoyaltyTransactions" DROP CONSTRAINT "FK_5e91c1253e8e230324528d5c652"`);
        await queryRunner.query(`ALTER TABLE "LoyaltyTransactions" DROP CONSTRAINT "FK_74c6d21c228fa315e0a1cb8ba52"`);
        await queryRunner.query(`ALTER TABLE "Orders" DROP CONSTRAINT "FK_229fceba3c9564ad81d8e7aeb78"`);
        await queryRunner.query(`ALTER TABLE "Orders" DROP CONSTRAINT "FK_61ed9f90daf27cb8aa7d72fe4d1"`);
        await queryRunner.query(`ALTER TABLE "Orders" DROP CONSTRAINT "FK_3966000a0b5d5bae146ff496c7b"`);
        await queryRunner.query(`ALTER TABLE "OrderItems" DROP CONSTRAINT "FK_5bdb51d8c4daf5a5dfd4b4e0b73"`);
        await queryRunner.query(`ALTER TABLE "OrderItems" DROP CONSTRAINT "FK_794bd0cca8310553df4714f699b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7242d523537887eedc8cce31e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08f97e9a05e74adaef6128b725"`);
        await queryRunner.query(`DROP TABLE "productcategories"`);
        await queryRunner.query(`DROP INDEX "public"."categories_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."categories_name_key"`);
        await queryRunner.query(`DROP INDEX "public"."ix_categories_parent_id"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP INDEX "public"."ix_products_name"`);
        await queryRunner.query(`DROP INDEX "public"."products_pkey"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP INDEX "public"."IX_CartItems_Cart_Id"`);
        await queryRunner.query(`DROP INDEX "public"."CartItems_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."IX_CartItems_Product_Id"`);
        await queryRunner.query(`DROP TABLE "CartItems"`);
        await queryRunner.query(`DROP INDEX "public"."Cart_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."Cart_guest_session_id_key"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Cart_User_Id"`);
        await queryRunner.query(`DROP TABLE "Cart"`);
        await queryRunner.query(`DROP INDEX "public"."unique_email"`);
        await queryRunner.query(`DROP INDEX "public"."users_email_key"`);
        await queryRunner.query(`DROP INDEX "public"."users_phone_number_key"`);
        await queryRunner.query(`DROP INDEX "public"."unique_phone"`);
        await queryRunner.query(`DROP INDEX "public"."users_pkey"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."addresses_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."ix_addresses_user_id"`);
        await queryRunner.query(`DROP TABLE "addresses"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Loyalty_Order_Id"`);
        await queryRunner.query(`DROP INDEX "public"."LoyaltyTransactions_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Loyalty_User_Id"`);
        await queryRunner.query(`DROP TABLE "LoyaltyTransactions"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Orders_Address_Id"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Orders_Slot_Id"`);
        await queryRunner.query(`DROP INDEX "public"."Orders_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Orders_Store_Id"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Orders_User_Id"`);
        await queryRunner.query(`DROP TABLE "Orders"`);
        await queryRunner.query(`DROP INDEX "public"."Stores_pkey"`);
        await queryRunner.query(`DROP TABLE "Stores"`);
        await queryRunner.query(`DROP INDEX "public"."DeliverySlots_pkey"`);
        await queryRunner.query(`DROP TABLE "DeliverySlots"`);
        await queryRunner.query(`DROP INDEX "public"."OrderItems_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."IX_OrderItems_Order_Id"`);
        await queryRunner.query(`DROP INDEX "public"."IX_OrderItems_Product_Id"`);
        await queryRunner.query(`DROP TABLE "OrderItems"`);
    }

}
