// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AppControllerCheckDbData, AppControllerCheckDbResponses, AppControllerGetHelloData, AppControllerGetHelloResponses, CartControllerAddToCartData, CartControllerAddToCartResponses, CartControllerClearData, CartControllerClearResponses, CartControllerGetCurrentData, CartControllerGetCurrentResponses, CartControllerRemoveItemData, CartControllerRemoveItemResponses, CategoriesControllerCreateData, CategoriesControllerCreateResponses, CategoriesControllerFindAllData, CategoriesControllerFindAllResponses, CategoriesControllerFindAllTreeData, CategoriesControllerFindAllTreeResponses, CategoriesControllerFindOneData, CategoriesControllerFindOneResponses, CategoriesControllerRemoveData, CategoriesControllerRemoveResponses, CategoriesControllerUpdateData, CategoriesControllerUpdateResponses, DeliverySlotsControllerFindTodayData, DeliverySlotsControllerFindTodayResponses, ProductsControllerFindAllData, ProductsControllerFindAllOptionsData, ProductsControllerFindAllOptionsResponses, ProductsControllerFindAllResponses, ProductsControllerFindOneData, ProductsControllerFindOneResponses, ProductsControllerFindSimilarData, ProductsControllerFindSimilarResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const appControllerGetHello = <ThrowOnError extends boolean = false>(options?: Options<AppControllerGetHelloData, ThrowOnError>) => (options?.client ?? client).get<AppControllerGetHelloResponses, unknown, ThrowOnError>({ url: '/', ...options });

export const appControllerCheckDb = <ThrowOnError extends boolean = false>(options?: Options<AppControllerCheckDbData, ThrowOnError>) => (options?.client ?? client).get<AppControllerCheckDbResponses, unknown, ThrowOnError>({ url: '/db-check', ...options });

export const categoriesControllerFindAll = <ThrowOnError extends boolean = false>(options?: Options<CategoriesControllerFindAllData, ThrowOnError>) => (options?.client ?? client).get<CategoriesControllerFindAllResponses, unknown, ThrowOnError>({ url: '/categories', ...options });

export const categoriesControllerCreate = <ThrowOnError extends boolean = false>(options: Options<CategoriesControllerCreateData, ThrowOnError>) => (options.client ?? client).post<CategoriesControllerCreateResponses, unknown, ThrowOnError>({
    url: '/categories',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const categoriesControllerFindAllTree = <ThrowOnError extends boolean = false>(options?: Options<CategoriesControllerFindAllTreeData, ThrowOnError>) => (options?.client ?? client).get<CategoriesControllerFindAllTreeResponses, unknown, ThrowOnError>({ url: '/categories/tree', ...options });

export const categoriesControllerRemove = <ThrowOnError extends boolean = false>(options: Options<CategoriesControllerRemoveData, ThrowOnError>) => (options.client ?? client).delete<CategoriesControllerRemoveResponses, unknown, ThrowOnError>({ url: '/categories/{id}', ...options });

export const categoriesControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<CategoriesControllerFindOneData, ThrowOnError>) => (options.client ?? client).get<CategoriesControllerFindOneResponses, unknown, ThrowOnError>({ url: '/categories/{id}', ...options });

export const categoriesControllerUpdate = <ThrowOnError extends boolean = false>(options: Options<CategoriesControllerUpdateData, ThrowOnError>) => (options.client ?? client).patch<CategoriesControllerUpdateResponses, unknown, ThrowOnError>({
    url: '/categories/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get current user cart based on session cookie
 */
export const cartControllerGetCurrent = <ThrowOnError extends boolean = false>(options?: Options<CartControllerGetCurrentData, ThrowOnError>) => (options?.client ?? client).get<CartControllerGetCurrentResponses, unknown, ThrowOnError>({ url: '/cart/current', ...options });

/**
 * Add item to cart; initializes session if missing
 */
export const cartControllerAddToCart = <ThrowOnError extends boolean = false>(options: Options<CartControllerAddToCartData, ThrowOnError>) => (options.client ?? client).post<CartControllerAddToCartResponses, unknown, ThrowOnError>({
    url: '/cart/add-item',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove specific item from cart
 */
export const cartControllerRemoveItem = <ThrowOnError extends boolean = false>(options: Options<CartControllerRemoveItemData, ThrowOnError>) => (options.client ?? client).delete<CartControllerRemoveItemResponses, unknown, ThrowOnError>({ url: '/cart/item/{itemId}', ...options });

/**
 * Remove all items from the current cart
 */
export const cartControllerClear = <ThrowOnError extends boolean = false>(options?: Options<CartControllerClearData, ThrowOnError>) => (options?.client ?? client).delete<CartControllerClearResponses, unknown, ThrowOnError>({ url: '/cart/clear', ...options });

/**
 * Find products with optional category, search, and filters
 */
export const productsControllerFindAll = <ThrowOnError extends boolean = false>(options?: Options<ProductsControllerFindAllData, ThrowOnError>) => (options?.client ?? client).get<ProductsControllerFindAllResponses, unknown, ThrowOnError>({ url: '/products', ...options });

/**
 * Get dynamic filter options based on search or category
 */
export const productsControllerFindAllOptions = <ThrowOnError extends boolean = false>(options?: Options<ProductsControllerFindAllOptionsData, ThrowOnError>) => (options?.client ?? client).get<ProductsControllerFindAllOptionsResponses, unknown, ThrowOnError>({ url: '/products/filter-options', ...options });

export const productsControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<ProductsControllerFindOneData, ThrowOnError>) => (options.client ?? client).get<ProductsControllerFindOneResponses, unknown, ThrowOnError>({ url: '/products/{id}', ...options });

/**
 * Get up to 15 similar products based on category
 */
export const productsControllerFindSimilar = <ThrowOnError extends boolean = false>(options: Options<ProductsControllerFindSimilarData, ThrowOnError>) => (options.client ?? client).get<ProductsControllerFindSimilarResponses, unknown, ThrowOnError>({ url: '/products/{id}/similar', ...options });

/**
 * Get available delivery slots for today
 */
export const deliverySlotsControllerFindToday = <ThrowOnError extends boolean = false>(options?: Options<DeliverySlotsControllerFindTodayData, ThrowOnError>) => (options?.client ?? client).get<DeliverySlotsControllerFindTodayResponses, unknown, ThrowOnError>({ url: '/delivery-slots/today', ...options });
