// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type CreateCategoryDto = {
    [key: string]: unknown;
};

export type UpdateCategoryDto = {
    [key: string]: unknown;
};

export type LoyaltyTransactions = {
    [key: string]: unknown;
};

export type DeliverySlots = {
    /**
     * Unique identifier for the delivery slot
     */
    slotId: number;
    /**
     * The beginning of the delivery window
     */
    startTime: string;
    /**
     * The end of the delivery window
     */
    endTime: string;
    /**
     * Whether this slot is still open for booking
     */
    isAvailable: boolean;
    orders?: Array<Orders>;
};

export type Stores = {
    /**
     * Unique identifier for the store
     */
    storeId: number;
    name: string;
    city: string;
    street: string;
    houseNumber: string;
    workingHours: string;
    orders?: Array<Orders>;
    /**
     * Latitude coordinate for map placement
     */
    lat: string;
    /**
     * Longitude coordinate for map placement
     */
    lng: string;
};

export type Orders = {
    orderId: number;
    userId: number | null;
    deliverySlotId: number | null;
    orderDate: string;
    status: string;
    /**
     * Total order cost
     */
    totalAmount: number;
    paymentMethod: string;
    deliveryAddressId?: number | null;
    storeId?: number | null;
    customerName?: string | null;
    customerPhone?: string | null;
    deliveryAddress?: string | null;
    deliveryDate?: string | null;
    comment?: string | null;
    isPaperless: boolean;
    deliverySlotStart?: string | null;
    deliverySlotEnd?: string | null;
    loyaltyTransactions?: Array<LoyaltyTransactions>;
    orderItems?: Array<OrderItems>;
    deliverySlot?: DeliverySlots;
    store?: Stores;
    user?: Users;
};

export type OrderItems = {
    /**
     * Unique identifier for the order item
     */
    itemId: number;
    orderId: number;
    productId: number;
    quantity: number;
    /**
     * Price captured at the exact moment of purchase
     */
    priceAtPurchase: number;
    order?: Orders;
    product?: Products;
};

export type Categories = {
    [key: string]: unknown;
};

export type Products = {
    productId: number;
    name: string;
    description?: string | null;
    /**
     * Current product price
     */
    price: number;
    qtyInStock: number;
    imgUrl?: string | null;
    brand?: string | null;
    originCountry?: string | null;
    isPromo: boolean;
    /**
     * Price before discount
     */
    oldPrice?: number | null;
    netContent?: number | null;
    unit?: string | null;
    cartItems: Array<CartItems>;
    orderItems: Array<OrderItems>;
    categories: Array<Categories>;
};

export type CartItems = {
    itemId: number;
    cartId: number;
    productId: number;
    quantity: number;
    cart: Cart;
    product: Products;
};

export type Cart = {
    /**
     * Unique identifier for the cart
     */
    cartId: number;
    userId?: number | null;
    guestSessionId?: string | null;
    user: Users | null;
    /**
     * List of items in the cart
     */
    cartItems: Array<CartItems>;
};

export type Addresses = {
    [key: string]: unknown;
};

export type Users = {
    userId: number;
    phoneNumber: string;
    email: string;
    name: string;
    carts: Array<Cart>;
    loyaltyTransactions: Array<LoyaltyTransactions>;
    orders: Array<Orders>;
    addresses: Array<Addresses>;
};

export type AddToCartDto = {
    /**
     * The ID of the product to add
     */
    productId: number;
    /**
     * Quantity of the product
     */
    quantity: number;
};

export type FilterOptionsDto = {
    minPrice: number;
    maxPrice: number;
    brands: Array<string>;
};

export type LoginDto = {
    [key: string]: unknown;
};

export type RegisterDto = {
    [key: string]: unknown;
};

export type CreateOrderDto = {
    [key: string]: unknown;
};

export type UpdateUserDto = {
    name?: string;
    phoneNumber?: string;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    200: unknown;
};

export type AppControllerCheckDbData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/db-check';
};

export type AppControllerCheckDbResponses = {
    200: unknown;
};

export type CategoriesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/categories';
};

export type CategoriesControllerFindAllResponses = {
    200: unknown;
};

export type CategoriesControllerCreateData = {
    body: CreateCategoryDto;
    path?: never;
    query?: never;
    url: '/categories';
};

export type CategoriesControllerCreateResponses = {
    201: unknown;
};

export type CategoriesControllerFindAllTreeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/categories/tree';
};

export type CategoriesControllerFindAllTreeResponses = {
    200: unknown;
};

export type CategoriesControllerRemoveData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/categories/{id}';
};

export type CategoriesControllerRemoveResponses = {
    200: unknown;
};

export type CategoriesControllerFindOneData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/categories/{id}';
};

export type CategoriesControllerFindOneResponses = {
    200: unknown;
};

export type CategoriesControllerUpdateData = {
    body: UpdateCategoryDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/categories/{id}';
};

export type CategoriesControllerUpdateResponses = {
    200: unknown;
};

export type CartControllerGetCurrentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cart/current';
};

export type CartControllerGetCurrentResponses = {
    200: Cart;
};

export type CartControllerGetCurrentResponse = CartControllerGetCurrentResponses[keyof CartControllerGetCurrentResponses];

export type CartControllerAddToCartData = {
    body: AddToCartDto;
    path?: never;
    query?: never;
    url: '/cart/add-item';
};

export type CartControllerAddToCartResponses = {
    200: Cart;
};

export type CartControllerAddToCartResponse = CartControllerAddToCartResponses[keyof CartControllerAddToCartResponses];

export type CartControllerRemoveItemData = {
    body?: never;
    path: {
        itemId: number;
    };
    query?: never;
    url: '/cart/item/{itemId}';
};

export type CartControllerRemoveItemResponses = {
    200: Cart;
};

export type CartControllerRemoveItemResponse = CartControllerRemoveItemResponses[keyof CartControllerRemoveItemResponses];

export type CartControllerClearData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cart/clear';
};

export type CartControllerClearResponses = {
    200: Cart;
};

export type CartControllerClearResponse = CartControllerClearResponses[keyof CartControllerClearResponses];

export type ProductsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        sort?: string;
        categoryId?: number;
        search?: string;
        minPrice?: number;
        maxPrice?: number;
        brands?: Array<string>;
        isPromo?: boolean;
    };
    url: '/products';
};

export type ProductsControllerFindAllResponses = {
    200: Array<Products>;
};

export type ProductsControllerFindAllResponse = ProductsControllerFindAllResponses[keyof ProductsControllerFindAllResponses];

export type ProductsControllerFindAllOptionsData = {
    body?: never;
    path?: never;
    query?: {
        categoryId?: number;
        search?: string;
    };
    url: '/products/filter-options';
};

export type ProductsControllerFindAllOptionsResponses = {
    200: FilterOptionsDto;
};

export type ProductsControllerFindAllOptionsResponse = ProductsControllerFindAllOptionsResponses[keyof ProductsControllerFindAllOptionsResponses];

export type ProductsControllerFindOneData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/products/{id}';
};

export type ProductsControllerFindOneResponses = {
    200: Products;
};

export type ProductsControllerFindOneResponse = ProductsControllerFindOneResponses[keyof ProductsControllerFindOneResponses];

export type ProductsControllerFindSimilarData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/products/{id}/similar';
};

export type ProductsControllerFindSimilarResponses = {
    200: Array<Products>;
};

export type ProductsControllerFindSimilarResponse = ProductsControllerFindSimilarResponses[keyof ProductsControllerFindSimilarResponses];

export type DeliverySlotsControllerFindByDateData = {
    body?: never;
    path?: never;
    query: {
        date: string;
    };
    url: '/delivery-slots';
};

export type DeliverySlotsControllerFindByDateResponses = {
    200: Array<DeliverySlots>;
};

export type DeliverySlotsControllerFindByDateResponse = DeliverySlotsControllerFindByDateResponses[keyof DeliverySlotsControllerFindByDateResponses];

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginResponses = {
    201: unknown;
};

export type AuthControllerRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthControllerRegisterResponses = {
    201: unknown;
};

export type OrdersControllerCreateData = {
    body: CreateOrderDto;
    path?: never;
    query?: never;
    url: '/orders';
};

export type OrdersControllerCreateResponses = {
    201: unknown;
};

export type OrdersControllerFindMyOrdersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/orders/my';
};

export type OrdersControllerFindMyOrdersResponses = {
    200: Array<Orders>;
};

export type OrdersControllerFindMyOrdersResponse = OrdersControllerFindMyOrdersResponses[keyof OrdersControllerFindMyOrdersResponses];

export type StoresControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stores';
};

export type StoresControllerFindAllResponses = {
    200: Array<Stores>;
};

export type StoresControllerFindAllResponse = StoresControllerFindAllResponses[keyof StoresControllerFindAllResponses];

export type UsersControllerGetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/profile';
};

export type UsersControllerGetProfileErrors = {
    /**
     * Invalid or missing token.
     */
    401: unknown;
};

export type UsersControllerGetProfileResponses = {
    /**
     * The user profile has been successfully retrieved.
     */
    200: Users;
};

export type UsersControllerGetProfileResponse = UsersControllerGetProfileResponses[keyof UsersControllerGetProfileResponses];

export type UsersControllerUpdateProfileData = {
    body: UpdateUserDto;
    path?: never;
    query?: never;
    url: '/users/profile';
};

export type UsersControllerUpdateProfileResponses = {
    200: Users;
};

export type UsersControllerUpdateProfileResponse = UsersControllerUpdateProfileResponses[keyof UsersControllerUpdateProfileResponses];
