// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type CreateCategoryDto = {
    [key: string]: unknown;
};

export type UpdateCategoryDto = {
    [key: string]: unknown;
};

export type CreateCartDto = {
    [key: string]: unknown;
};

export type Users = {
    [key: string]: unknown;
};

export type Cart = {
    /**
     * Unique identifier for the cart
     */
    cartId: number;
    userId?: number | null;
    guestSessionId?: string | null;
    user: Users | null;
    /**
     * List of items in the cart
     */
    cartItems: Array<CartItems>;
};

export type OrderItems = {
    [key: string]: unknown;
};

export type Categories = {
    [key: string]: unknown;
};

export type Products = {
    productId: number;
    name: string;
    description?: string | null;
    /**
     * Current product price
     */
    price: number;
    qtyInStock: number;
    imgUrl?: string | null;
    brand?: string | null;
    originCountry?: string | null;
    isPromo: boolean;
    /**
     * Price before discount
     */
    oldPrice?: number | null;
    netContent?: number | null;
    unit?: string | null;
    cartItems: Array<CartItems>;
    orderItems: Array<OrderItems>;
    categories: Array<Categories>;
};

export type CartItems = {
    itemId: number;
    cartId: number;
    productId: number;
    quantity: number;
    cart: Cart;
    product: Products;
};

export type AddToCartDto = {
    /**
     * The ID of the product to add
     */
    productId: number;
    /**
     * Quantity of the product
     */
    quantity: number;
};

export type UpdateCartDto = {
    [key: string]: unknown;
};

export type CreateCartItemDto = {
    [key: string]: unknown;
};

export type UpdateCartItemDto = {
    [key: string]: unknown;
};

export type FilterOptionsDto = {
    minPrice: number;
    maxPrice: number;
    brands: Array<string>;
};

export type CreateDeliverySlotDto = {
    [key: string]: unknown;
};

export type UpdateDeliverySlotDto = {
    [key: string]: unknown;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    200: unknown;
};

export type AppControllerCheckDbData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/db-check';
};

export type AppControllerCheckDbResponses = {
    200: unknown;
};

export type CategoriesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/categories';
};

export type CategoriesControllerFindAllResponses = {
    200: unknown;
};

export type CategoriesControllerCreateData = {
    body: CreateCategoryDto;
    path?: never;
    query?: never;
    url: '/categories';
};

export type CategoriesControllerCreateResponses = {
    201: unknown;
};

export type CategoriesControllerFindAllTreeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/categories/tree';
};

export type CategoriesControllerFindAllTreeResponses = {
    200: unknown;
};

export type CategoriesControllerRemoveData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/categories/{id}';
};

export type CategoriesControllerRemoveResponses = {
    200: unknown;
};

export type CategoriesControllerFindOneData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/categories/{id}';
};

export type CategoriesControllerFindOneResponses = {
    200: unknown;
};

export type CategoriesControllerUpdateData = {
    body: UpdateCategoryDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/categories/{id}';
};

export type CategoriesControllerUpdateResponses = {
    200: unknown;
};

export type CartControllerCreateData = {
    body: CreateCartDto;
    path?: never;
    query?: never;
    url: '/cart';
};

export type CartControllerCreateResponses = {
    201: unknown;
};

export type CartControllerGetCurrentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cart/current';
};

export type CartControllerGetCurrentResponses = {
    200: Cart;
};

export type CartControllerGetCurrentResponse = CartControllerGetCurrentResponses[keyof CartControllerGetCurrentResponses];

export type CartControllerAddToCartData = {
    body: AddToCartDto;
    path?: never;
    query?: never;
    url: '/cart/add-item';
};

export type CartControllerAddToCartResponses = {
    200: Cart;
};

export type CartControllerAddToCartResponse = CartControllerAddToCartResponses[keyof CartControllerAddToCartResponses];

export type CartControllerRemoveItemData = {
    body?: never;
    path: {
        itemId: number;
    };
    query?: never;
    url: '/cart/item/{itemId}';
};

export type CartControllerRemoveItemResponses = {
    200: Cart;
};

export type CartControllerRemoveItemResponse = CartControllerRemoveItemResponses[keyof CartControllerRemoveItemResponses];

export type CartControllerRemoveData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/cart/{id}';
};

export type CartControllerRemoveResponses = {
    200: unknown;
};

export type CartControllerUpdateData = {
    body: UpdateCartDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/cart/{id}';
};

export type CartControllerUpdateResponses = {
    200: unknown;
};

export type CartItemsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cart-items';
};

export type CartItemsControllerFindAllResponses = {
    200: unknown;
};

export type CartItemsControllerCreateData = {
    body: CreateCartItemDto;
    path?: never;
    query?: never;
    url: '/cart-items';
};

export type CartItemsControllerCreateResponses = {
    201: unknown;
};

export type CartItemsControllerRemoveData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/cart-items/{id}';
};

export type CartItemsControllerRemoveResponses = {
    200: unknown;
};

export type CartItemsControllerFindOneData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/cart-items/{id}';
};

export type CartItemsControllerFindOneResponses = {
    200: unknown;
};

export type CartItemsControllerUpdateData = {
    body: UpdateCartItemDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/cart-items/{id}';
};

export type CartItemsControllerUpdateResponses = {
    200: unknown;
};

export type ProductsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        sort?: string;
        categoryId?: number;
        search?: string;
        minPrice?: number;
        maxPrice?: number;
        brands?: Array<string>;
        isPromo?: boolean;
    };
    url: '/products';
};

export type ProductsControllerFindAllResponses = {
    200: Array<Products>;
};

export type ProductsControllerFindAllResponse = ProductsControllerFindAllResponses[keyof ProductsControllerFindAllResponses];

export type ProductsControllerFindAllOptionsData = {
    body?: never;
    path?: never;
    query?: {
        categoryId?: number;
        search?: string;
    };
    url: '/products/filter-options';
};

export type ProductsControllerFindAllOptionsResponses = {
    200: FilterOptionsDto;
};

export type ProductsControllerFindAllOptionsResponse = ProductsControllerFindAllOptionsResponses[keyof ProductsControllerFindAllOptionsResponses];

export type ProductsControllerFindOneData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/products/{id}';
};

export type ProductsControllerFindOneResponses = {
    200: Products;
};

export type ProductsControllerFindOneResponse = ProductsControllerFindOneResponses[keyof ProductsControllerFindOneResponses];

export type ProductsControllerFindSimilarData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/products/{id}/similar';
};

export type ProductsControllerFindSimilarResponses = {
    200: Array<Products>;
};

export type ProductsControllerFindSimilarResponse = ProductsControllerFindSimilarResponses[keyof ProductsControllerFindSimilarResponses];

export type DeliverySlotsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/delivery-slots';
};

export type DeliverySlotsControllerFindAllResponses = {
    200: unknown;
};

export type DeliverySlotsControllerCreateData = {
    body: CreateDeliverySlotDto;
    path?: never;
    query?: never;
    url: '/delivery-slots';
};

export type DeliverySlotsControllerCreateResponses = {
    201: unknown;
};

export type DeliverySlotsControllerRemoveData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/delivery-slots/{id}';
};

export type DeliverySlotsControllerRemoveResponses = {
    200: unknown;
};

export type DeliverySlotsControllerFindOneData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/delivery-slots/{id}';
};

export type DeliverySlotsControllerFindOneResponses = {
    200: unknown;
};

export type DeliverySlotsControllerUpdateData = {
    body: UpdateDeliverySlotDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/delivery-slots/{id}';
};

export type DeliverySlotsControllerUpdateResponses = {
    200: unknown;
};
